# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
