# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='foto',
            field=models.FileField(upload_to='home/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
