# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_auto_20170904_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeinfo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
