# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
