# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendamento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atividade_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividade.AtividadeInfo'),
        ),
    ]
